<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RootNamespace>Xenial.Delicious</RootNamespace>
    <PackageId>Xenial.Tasty.Core</PackageId>
    <PackageDescription>Tasty Core - Delicious dotnet testing</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" Version="2.24.84" />
  </ItemGroup>

  <ItemGroup>
    <None Include="THIRD-PARTY-NOTICES.TXT">
      <Pack>true</Pack>
      <PackagePath></PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>
  
</Project>
