pull_request_rules:
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
#  - name: Automatic merge on approval
#    conditions:
#      - "#approved-reviews-by>=1"
#    actions:
#      merge:
#        method: merge
